const MAILCHIMP_CLIENT_ID = "";
const MAILCHIMP_CLIENT_SECRET="";
const BASE_URL="http://127.0.0.1:4080"
const CODE=""

exports.MAILCHIMP_CLIENT_ID = MAILCHIMP_CLIENT_ID
exports.BASE_URL = BASE_URL
exports.MAILCHIMP_CLIENT_SECRET = MAILCHIMP_CLIENT_SECRET